import { openai } from "@/config/ai";
import { NFT_METADATA_PROMPT } from "@/constants/aiPrompt";

export const nftService = {
  async generateNFT(prompt: string) {
    const textRes = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: NFT_METADATA_PROMPT.toMessages(prompt),
      response_format: { type: "json_object" },
    });

    const parsed = JSON.parse(textRes.choices[0].message?.content ?? "{}");

    const title = parsed.title || "Untitled NFT";
    const description = parsed.description || prompt;

    const imageRes = await openai.images.generate({
      model: "gpt-image-1",
      prompt: `NFT art: ${prompt}`,
    });

    if (!imageRes.data || imageRes.data.length === 0) {
      throw new Error("No image generated by OpenAI");
    }

    const image_base64 = imageRes.data[0].b64_json!;
    const imageDataUri = `data:image/png;base64,${image_base64}`;

    return {
      title,
      description,
      image: imageDataUri,
    };
  },
};
